#!/bin/bash
# Doom Emacs Skill 安装后提示

echo ""
echo "🎉 Doom Emacs Skill 安装完成！"
echo "========================================"
echo ""
echo "🚀 快速开始指南："
echo ""
echo "1. 启动 Emacs daemon:"
echo "   emacs --daemon"
echo ""
echo "2. 连接到 Emacs:"
echo "   emacsclient -c    # 图形界面"
echo "   emacsclient -t    # 终端界面"
echo ""
echo "3. 核心快捷键速查："
echo "   📁 SPC f f - 查找文件"
echo "   💻 SPC c d - 跳转到定义"
echo "   🔍 SPC c D - 查找引用"
echo "   🤖 M-x gptel - 打开 AI 聊天"
echo "   🆘 SPC h k - 查看按键帮助"
echo ""
echo "4. 验证安装："
echo "   doombridge health-check"
echo ""
echo "5. 学习资源："
echo "   - 查看完整速查表: references/doom-cheatsheet.md"
echo "   - 按 SPC h k 学习任何快捷键"
echo "   - 访问社区获取帮助"
echo ""
echo "========================================"
echo "💡 提示：每天练习 10 分钟，一周内形成肌肉记忆！"
echo ""

# 检查是否在交互式 shell 中
if [ -t 0 ]; then
    read -p "是否显示核心快捷键示例？(y/n): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo ""
        echo "🎯 核心快捷键示例："
        echo ""
        echo "代码分析工作流："
        echo "1. SPC f f ~/code/redis/src/dict.c"
        echo "2. 将光标放在 dictFind 上"
        echo "3. SPC c d - 跳转到定义"
        echo "4. SPC c D - 查找所有引用"
        echo "5. M-x gptel - 使用 AI 分析代码"
        echo ""
        echo "文件管理："
        echo "• SPC b b - 切换缓冲区"
        echo "• SPC p p - 切换项目"
        echo "• SPC w h/j/k/l - 移动窗口"
        echo ""
        echo "搜索导航："
        echo "• SPC s s - 全文搜索"
        echo "• SPC s i - 跳转到符号"
        echo "• SPC s j - 跳转到行"
        echo ""
    fi
fi

echo "✨ 开始你的 Doom Emacs 之旅吧！"